// ============================================
// 魔女卡牌 — 因子配置 v3 (九元素体系)
// 地火水风光暗人神以太
// ============================================
import type { FactorDef, ConflictFusionRule, ResonanceRule, ElementType } from '../types';

// ============ 全部因子 ============
export const BASE_FACTORS: FactorDef[] = [

  // ═══════ 地 (5) ═══════
  { id:'地', element:'地', level:'N',
    promptZh:'大地之力,厚重魔力', promptEn:'earth power, heavy magic',
    stats:{ atk:0, def:10, spd:-5, hp:10, mp:2, crit:0, dodge:0 },
    description:'基础地元素' },
  { id:'岩石', element:'地', level:'R',
    promptZh:'岩石堡垒,大地脉动', promptEn:'stone bastion, earth pulse',
    stats:{ atk:4, def:22, spd:-5, hp:28, mp:5, crit:2, dodge:0 },
    skill:{ name:'地裂', type:'active', target:'all_enemies', effect:'DEF×2.0全体', mpCost:20, multiplier:2.0, defBased:true, desc:'撕裂大地，以防御力碾压全体敌人' },
    description:'大地脉动的岩石结晶' },
  { id:'山岳', element:'地', level:'SR',
    promptZh:'山岳崩塌之力', promptEn:'mountain collapse, landslide',
    stats:{ atk:8, def:35, spd:-6, hp:48, mp:8, crit:4, dodge:0 },
    skill:{ name:'山崩', type:'active', target:'all_enemies', effect:'DEF×3.0全体', mpCost:28, multiplier:3.0, defBased:true, desc:'山岳崩塌，大地怒吼' },
    description:'山岳崩塌，大地怒吼' },
  { id:'地核', element:'地', level:'SSR',
    promptZh:'地核爆裂撼动大地', promptEn:'planetary core eruption',
    stats:{ atk:14, def:52, spd:-8, hp:80, mp:14, crit:6, dodge:0 },
    passive:'受到的物理伤害-20%',
    skill:{ name:'地核爆裂', type:'active', target:'all_enemies', effect:'DEF×3.8全体+敌全体SPD-15', mpCost:40, multiplier:3.8, defBased:true, desc:'地核之力喷涌而出' },
    description:'地核之力喷涌而出' },
  { id:'星核', element:'地', level:'UR',
    promptZh:'星球之核重力碾压', promptEn:'planetary core, gravity crush',
    stats:{ atk:24, def:75, spd:-10, hp:140, mp:22, crit:10, dodge:0 },
    passive:'受到的物理伤害-30%',
    skill:{ name:'星核重压', type:'active', target:'all_enemies', effect:'DEF×5.0全体+眩晕1回合', mpCost:55, multiplier:5.0, defBased:true, statusEffect:'stun', desc:'星球之核的引力碾碎一切' },
    description:'星球之核的引力碾碎一切' },

  // ═══════ 火 (5) ═══════
  { id:'火', element:'火', level:'N',
    promptZh:'火焰环绕,赤红魔力', promptEn:'flame aura, crimson magic',
    stats:{ atk:8, def:0, spd:3, hp:0, mp:8, crit:2, dodge:0 },
    description:'基础火元素' },
  { id:'烈焰', element:'火', level:'R',
    promptZh:'烈焰爆发,灼热难耐', promptEn:'blazing eruption, searing heat',
    stats:{ atk:22, def:3, spd:6, hp:5, mp:14, crit:8, dodge:0 },
    skill:{ name:'爆裂火球', type:'active', target:'single_enemy', effect:'ATK×1.8+灼烧2回合', mpCost:15, multiplier:1.8, statusEffect:'burn', desc:'压缩火焰爆裂，附加灼烧' },
    description:'高密度火焰的压缩体' },
  { id:'爆炎', element:'火', level:'SR',
    promptZh:'爆炎炸裂,烈焰风暴', promptEn:'detonating blaze, firestorm',
    stats:{ atk:40, def:5, spd:12, hp:15, mp:20, crit:15, dodge:0 },
    skill:{ name:'爆炎风暴', type:'active', target:'all_enemies', effect:'ATK×2.2全体+灼烧', mpCost:25, multiplier:2.2, statusEffect:'burn', desc:'压缩爆炎化为火焰风暴' },
    description:'压缩到极致的爆炎，释放时横扫一切' },
  { id:'阳炎', element:'火', level:'SSR',
    promptZh:'太阳表面之火', promptEn:'solar flame, miniature sun',
    stats:{ atk:65, def:10, spd:16, hp:30, mp:35, crit:26, dodge:0 },
    passive:'火属性伤害+25%',
    skill:{ name:'太阳火', type:'active', target:'single_enemy', effect:'ATK×3.2单体·无视50%防', mpCost:30, multiplier:3.2, pierceDef:0.5, desc:'太阳之火凝为一点' },
    description:'太阳之火凝为一点' },
  { id:'凤凰火', element:'火', level:'UR',
    promptZh:'不死鸟涅槃重生', promptEn:'phoenix rebirth, divine flame',
    stats:{ atk:110, def:18, spd:24, hp:55, mp:50, crit:38, dodge:5 },
    passive:'死亡后以50%HP复活1次',
    skill:{ name:'涅槃', type:'active', target:'all_enemies', effect:'ATK×4.0全体', mpCost:50, multiplier:4.0, desc:'凤凰涅槃，燃尽后重生' },
    description:'凤凰涅槃，燃尽后重生' },

  // ═══════ 水（含水系+冰系，10）═══════
  { id:'水', element:'水', level:'N',
    promptZh:'水流环绕,碧蓝魔力', promptEn:'water aura, azure magic',
    stats:{ atk:3, def:3, spd:0, hp:8, mp:8, crit:1, dodge:1 },
    description:'基础水元素' },
  { id:'冰', element:'水', level:'N',
    promptZh:'冰晶凝结,浅蓝魔力', promptEn:'ice crystals, pale blue magic',
    stats:{ atk:4, def:6, spd:-2, hp:4, mp:6, crit:2, dodge:0 },
    description:'水之固态，基础冰元素' },
  { id:'激流', element:'水', level:'R',
    promptZh:'激流奔涌,碧蓝狂潮', promptEn:'raging torrent, azure surge',
    stats:{ atk:10, def:8, spd:8, hp:12, mp:14, crit:3, dodge:3 },
    skill:{ name:'水龙卷', type:'active', target:'all_enemies', effect:'ATK×1.5全体', mpCost:18, multiplier:1.5, desc:'激流化为水龙卷' },
    description:'奔涌不息的激流' },
  { id:'极寒', element:'水', level:'R',
    promptZh:'极寒冰狱,绝对零度', promptEn:'frozen prison, absolute zero',
    stats:{ atk:6, def:18, spd:0, hp:16, mp:12, crit:3, dodge:0 },
    skill:{ name:'冰封结界', type:'active', target:'all_enemies', effect:'DEF×2.0全体', mpCost:18, multiplier:2.0, defBased:true, desc:'极寒结界冻结全场' },
    description:'绝对零度的寒气' },
  { id:'深渊', element:'水', level:'SR',
    promptZh:'深渊暗流吞噬一切', promptEn:'abyssal maelstrom, deep vortex',
    stats:{ atk:18, def:14, spd:12, hp:25, mp:22, crit:6, dodge:5 },
    skill:{ name:'深渊漩涡', type:'active', target:'all_enemies', effect:'ATK×2.2全体+减速2回合', mpCost:28, multiplier:2.2, statusEffect:'slow', desc:'来自无尽深渊的吞噬漩涡' },
    description:'来自无尽深渊的吞噬漩涡' },
  { id:'玄冰', element:'水', level:'SR',
    promptZh:'千年玄冰化为壁障', promptEn:'black ice, ancient frost',
    stats:{ atk:10, def:28, spd:2, hp:28, mp:18, crit:5, dodge:0 },
    skill:{ name:'玄冰壁障', type:'active', target:'all_enemies', effect:'DEF×2.5全体', mpCost:28, multiplier:2.5, defBased:true, desc:'千年玄冰凝成的壁障' },
    description:'千年玄冰凝成的壁障' },
  { id:'沧溟', element:'水', level:'SSR',
    promptZh:'沧溟之海吞噬大地', promptEn:'vast ocean tidal wave',
    stats:{ atk:30, def:22, spd:18, hp:45, mp:35, crit:10, dodge:8 },
    passive:'水属性伤害+25%',
    skill:{ name:'沧溟潮汐', type:'active', target:'all_enemies', effect:'ATK×3.0全体·回复自身30%HP', mpCost:38, multiplier:3.0, desc:'沧溟之力化为吞噬一切的潮汐' },
    description:'沧溟之力化为吞噬一切的潮汐' },
  { id:'永冻', element:'水', level:'SSR',
    promptZh:'永冻冰狱封绝万物', promptEn:'eternal frost, frozen hell',
    stats:{ atk:18, def:42, spd:4, hp:48, mp:28, crit:8, dodge:0 },
    passive:'受物理伤害-15%',
    skill:{ name:'永冻冰狱', type:'active', target:'all_enemies', effect:'DEF×3.2全体+冻结1回合', mpCost:38, multiplier:3.2, defBased:true, statusEffect:'freeze', desc:'永恒冰封的地狱' },
    description:'永恒冰封的地狱' },
  { id:'归墟', element:'水', level:'UR',
    promptZh:'万物归墟归于虚无', promptEn:'return to void, cosmic ocean',
    stats:{ atk:50, def:35, spd:25, hp:80, mp:50, crit:15, dodge:12 },
    passive:'受到伤害的15%反弹给攻击者',
    skill:{ name:'归墟', type:'active', target:'all_enemies', effect:'ATK×3.5全体·敌全体DEF-20%', mpCost:50, multiplier:3.5, statusEffect:'def_down', desc:'万物终将归于虚无之海' },
    description:'万物终将归于虚无之海' },
  { id:'绝对零度', element:'水', level:'UR',
    promptZh:'绝对零度封绝宇宙', promptEn:'absolute zero, cosmic cold',
    stats:{ atk:30, def:60, spd:6, hp:85, mp:40, crit:12, dodge:0 },
    passive:'受到物理伤害-25%',
    skill:{ name:'绝对零度', type:'active', target:'all_enemies', effect:'DEF×4.5全体+冻结', mpCost:55, multiplier:4.5, defBased:true, statusEffect:'freeze', desc:'绝对零度的寒气' },
    description:'绝对零度的寒气' },

  // ═══════ 风（含风系+雷系，10）═══════
  { id:'风', element:'风', level:'N',
    promptZh:'疾风环绕,翠绿魔力', promptEn:'wind aura, emerald magic',
    stats:{ atk:5, def:0, spd:8, hp:0, mp:5, crit:3, dodge:2 },
    description:'基础风元素' },
  { id:'雷', element:'风', level:'N',
    promptZh:'雷光闪烁,金黄魔力', promptEn:'thunder sparks, golden magic',
    stats:{ atk:10, def:0, spd:5, hp:0, mp:3, crit:5, dodge:0 },
    description:'风之电气，基础雷元素' },
  { id:'暴风', element:'风', level:'R',
    promptZh:'暴风怒号,翠绿风暴', promptEn:'howling gale, emerald tempest',
    stats:{ atk:14, def:2, spd:22, hp:4, mp:10, crit:10, dodge:12 },
    skill:{ name:'风刃乱舞', type:'active', target:'random_enemy', effect:'3连击·ATK×0.8', mpCost:14, multiplier:0.8, hits:3, desc:'暴风化为利刃' },
    description:'撕裂大气的风暴' },
  { id:'雷霆', element:'风', level:'R',
    promptZh:'雷霆万钧', promptEn:'thundering might, lightning burst',
    stats:{ atk:26, def:0, spd:14, hp:3, mp:12, crit:18, dodge:0 },
    skill:{ name:'天雷击', type:'active', target:'single_enemy', effect:'ATK×2.2+眩晕', mpCost:20, multiplier:2.2, statusEffect:'stun', desc:'召唤天雷劈下' },
    description:'天穹降下的雷霆' },
  { id:'飓风', element:'风', level:'SR',
    promptZh:'飓风之眼割裂一切', promptEn:'hurricane eye, tornado',
    stats:{ atk:25, def:4, spd:35, hp:10, mp:15, crit:18, dodge:18 },
    skill:{ name:'飓风之眼', type:'active', target:'random_enemy', effect:'5连击·ATK×0.6', mpCost:25, multiplier:0.6, hits:5, desc:'五道风刃割裂战场' },
    description:'暴风之核' },
  { id:'劫雷', element:'风', level:'SR',
    promptZh:'天劫之雷直劈而下', promptEn:'calamity lightning, divine bolt',
    stats:{ atk:45, def:2, spd:22, hp:8, mp:18, crit:28, dodge:0 },
    skill:{ name:'劫雷', type:'active', target:'single_enemy', effect:'ATK×3.0单体+眩晕', mpCost:28, multiplier:3.0, statusEffect:'stun', desc:'天劫之雷' },
    description:'天劫之雷' },
  { id:'虚空风', element:'风', level:'SSR',
    promptZh:'虚空裂隙撕裂时空', promptEn:'void gale, dimensional tear',
    stats:{ atk:45, def:8, spd:50, hp:20, mp:25, crit:28, dodge:25 },
    passive:'风属性伤害+25%',
    skill:{ name:'虚空裂隙', type:'active', target:'random_enemy', effect:'8连击·ATK×0.5随机', mpCost:35, multiplier:0.5, hits:8, pierceDef:0.3, desc:'虚空裂隙' },
    description:'虚空裂隙' },
  { id:'天罚', element:'风', level:'SSR',
    promptZh:'天罚神雷降世', promptEn:'divine punishment, heaven bolt',
    stats:{ atk:78, def:5, spd:30, hp:18, mp:28, crit:40, dodge:0 },
    passive:'雷属性伤害+25%',
    skill:{ name:'天罚', type:'active', target:'single_enemy', effect:'ATK×3.8单体·必暴+眩晕', mpCost:38, multiplier:3.8, statusEffect:'stun', desc:'天降神罚之雷' },
    description:'天降神罚之雷' },
  { id:'时空风暴', element:'风', level:'UR',
    promptZh:'时空风暴碾碎维度', promptEn:'spacetime storm, temporal collapse',
    stats:{ atk:75, def:14, spd:70, hp:38, mp:38, crit:38, dodge:35 },
    passive:'基础行动速度+30%',
    skill:{ name:'时空崩坏', type:'active', target:'random_enemy', effect:'10连击·ATK×0.5随机+时停2回合', mpCost:50, multiplier:0.5, hits:10, statusEffect:'freeze', desc:'扭曲时空的风暴' },
    description:'扭曲时空的风暴' },
  { id:'混沌雷', element:'风', level:'UR',
    promptZh:'混沌初开雷霆万钧', promptEn:'primordial chaos lightning',
    stats:{ atk:130, def:10, spd:38, hp:35, mp:42, crit:55, dodge:0 },
    passive:'暴击伤害+50%',
    skill:{ name:'混沌雷暴', type:'active', target:'single_enemy', effect:'ATK×5.0单体·无视防御·必暴', mpCost:55, multiplier:5.0, pierceDef:1.0, desc:'混沌初开时诞生的原始雷电' },
    description:'混沌初开时诞生的原始雷电' },

  // ═══════ 光 (5) ═══════
  { id:'光', element:'光', level:'N',
    promptZh:'柔光普照,金色魔力', promptEn:'gentle light, golden magic',
    stats:{ atk:0, def:5, spd:2, hp:6, mp:6, crit:0, dodge:0 },
    description:'基础光元素' },
  { id:'圣光', element:'光', level:'R',
    promptZh:'圣光降临,金色庇护', promptEn:'holy light descends, golden blessing',
    stats:{ atk:4, def:10, spd:6, hp:16, mp:20, crit:0, dodge:0 },
    skill:{ name:'光之守护', type:'active', target:'all_allies', effect:'回复ATK×2.0+全体DEF+5·2回合', mpCost:16, multiplier:2.0, desc:'圣光笼罩全员' },
    description:'纯净圣光' },
  { id:'神辉', element:'光', level:'SR',
    promptZh:'神之光辉驱散诅咒', promptEn:'divine radiance, holy blessing',
    stats:{ atk:8, def:16, spd:10, hp:28, mp:30, crit:2, dodge:0 },
    skill:{ name:'神辉祝福', type:'active', target:'all_allies', effect:'回复全体HP·ATK×3.0+清除debuff', mpCost:28, multiplier:3.0, desc:'神辉普照' },
    description:'神辉普照' },
  { id:'天光', element:'光', level:'SSR',
    promptZh:'天堂之光照耀众生', promptEn:'heavenly light, divine grace',
    stats:{ atk:14, def:24, spd:15, hp:48, mp:42, crit:4, dodge:2 },
    passive:'回合结束回复自身5%HP',
    skill:{ name:'天光', type:'active', target:'all_allies', effect:'回复全体·ATK×4.0+全体DEF+15', mpCost:40, multiplier:4.0, desc:'天堂之光' },
    description:'天堂之光' },
  { id:'创世之光', element:'光', level:'UR',
    promptZh:'创世之初的第一道光', promptEn:'creation light, genesis',
    stats:{ atk:24, def:36, spd:22, hp:85, mp:58, crit:8, dodge:5 },
    passive:'回合结束回复全体5%HP',
    skill:{ name:'创世之光', type:'active', target:'all_allies', effect:'复活1队友+全体回复', mpCost:65, multiplier:5.0, desc:'创世之初的光芒' },
    description:'创世之初的光芒' },

  // ═══════ 暗 (5) ═══════
  { id:'暗', element:'暗', level:'N',
    promptZh:'暗影弥漫,紫黑魔力', promptEn:'shadow aura, dark purple magic',
    stats:{ atk:7, def:0, spd:4, hp:0, mp:7, crit:4, dodge:1 },
    description:'基础暗元素' },
  { id:'暗影', element:'暗', level:'R',
    promptZh:'暗影深渊,黑幕笼罩', promptEn:'abyssal shadow, dark shroud',
    stats:{ atk:18, def:4, spd:10, hp:6, mp:12, crit:14, dodge:5 },
    skill:{ name:'暗影突刺', type:'active', target:'single_enemy', effect:'ATK×2.0·无视50%防御', mpCost:17, multiplier:2.0, pierceDef:0.5, desc:'从阴影中刺出致命一击' },
    description:'深渊暗影的化身' },
  { id:'冥暗', element:'暗', level:'SR',
    promptZh:'冥界暗影吞噬生命', promptEn:'underworld darkness, soul eater',
    stats:{ atk:32, def:7, spd:16, hp:12, mp:18, crit:22, dodge:8 },
    skill:{ name:'冥暗吞噬', type:'active', target:'single_enemy', effect:'ATK×2.5单体·吸收30%伤害为HP', mpCost:26, multiplier:2.5, pierceDef:0.5, desc:'冥界深渊的影子' },
    description:'冥界深渊的影子' },
  { id:'虚无', element:'暗', level:'SSR',
    promptZh:'虚无之力湮灭一切', promptEn:'void obliteration, nothingness',
    stats:{ atk:55, def:12, spd:24, hp:25, mp:28, crit:32, dodge:14 },
    passive:'暗属性伤害+25%',
    skill:{ name:'虚无湮灭', type:'active', target:'single_enemy', effect:'ATK×3.5单体·无视80%防', mpCost:38, multiplier:3.5, pierceDef:0.8, desc:'虚无之力' },
    description:'虚无之力' },
  { id:'湮灭', element:'暗', level:'UR',
    promptZh:'彻底湮灭不复存在', promptEn:'annihilation, erasure from existence',
    stats:{ atk:95, def:20, spd:34, hp:48, mp:42, crit:45, dodge:20 },
    passive:'击杀回复自身30%HP',
    skill:{ name:'湮灭', type:'active', target:'single_enemy', effect:'ATK×5.0单体', mpCost:55, multiplier:5.0, pierceDef:1.0, desc:'将目标从存在中抹去' },
    description:'将目标从存在中彻底抹去' },

  // ═══════ 人 (7) ═══════
  { id:'猛攻', element:'人', level:'N',
    promptZh:'猛攻之势', promptEn:'aggressive stance',
    stats:{ atk:10, def:-3, spd:2, hp:0, mp:0, crit:3, dodge:-1 },
    description:'牺牲防御换取高攻' },
  { id:'精准', element:'人', level:'N',
    promptZh:'精准打击', promptEn:'precise strike',
    stats:{ atk:5, def:0, spd:3, hp:2, mp:0, crit:8, dodge:0 },
    description:'高暴击，稳定输出' },
  { id:'守护', element:'人', level:'N',
    promptZh:'守护之盾', promptEn:'guardian shield',
    stats:{ atk:-3, def:12, spd:-2, hp:8, mp:0, crit:0, dodge:0 },
    description:'高防御，适合前排' },
  { id:'游击', element:'人', level:'N',
    promptZh:'游击战术', promptEn:'hit and run tactics',
    stats:{ atk:6, def:-5, spd:10, hp:0, mp:0, crit:2, dodge:5 },
    description:'高闪避，高速游击' },
  { id:'反击', element:'人', level:'R',
    promptZh:'反击架势', promptEn:'counter stance',
    stats:{ atk:6, def:8, spd:-2, hp:5, mp:0, crit:0, dodge:0 },
    passive:'受击时20%概率反击ATK×0.5',
    description:'以守为攻的战斗技巧' },
  { id:'坚韧', element:'人', level:'R',
    promptZh:'坚韧不拔', promptEn:'unyielding',
    stats:{ atk:0, def:12, spd:0, hp:15, mp:0, crit:0, dodge:0 },
    passive:'HP低于30%时DEF+30%',
    description:'绝境中爆发顽强生命力' },
  { id:'咆哮', element:'人', level:'SR',
    promptZh:'战吼咆哮', promptEn:'war roar',
    stats:{ atk:12, def:5, spd:5, hp:10, mp:5, crit:5, dodge:0 },
    skill:{ name:'战吼', type:'active', target:'all_allies', effect:'全队ATK+25% 2回合', mpCost:20, desc:'怒吼激励全队战力' },
    description:'怒吼激励全队战力' },

  // ═══════ 神 (4) ═══════
  { id:'治愈', element:'神', level:'N',
    promptZh:'治愈魔法', promptEn:'healing magic',
    stats:{ atk:0, def:2, spd:1, hp:5, mp:8, crit:0, dodge:0 },
    skill:{ name:'治愈术', type:'active', target:'single_ally', effect:'回复HP', mpCost:10, multiplier:1.0, desc:'单体回复' },
    description:'基础治疗魔法' },
  { id:'增幅', element:'神', level:'R',
    promptZh:'魔力增幅', promptEn:'magic amplification',
    stats:{ atk:3, def:2, spd:2, hp:2, mp:10, crit:0, dodge:0 },
    skill:{ name:'魔力增幅', type:'active', target:'all_allies', effect:'全队ATK+25% 2回合', mpCost:15, desc:'强化全队的魔力' },
    description:'强化全队的魔力' },
  { id:'结界', element:'神', level:'SR',
    promptZh:'魔法结界', promptEn:'magic barrier',
    stats:{ atk:0, def:15, spd:-5, hp:10, mp:20, crit:0, dodge:0 },
    skill:{ name:'魔法结界', type:'active', target:'all_allies', effect:'全队减伤30% 2回合', mpCost:25, desc:'守护全队的魔法屏障' },
    description:'守护全队的魔法屏障' },
  { id:'王之力', element:'神', level:'SR',
    promptZh:'王者之力', promptEn:'king\'s power',
    stats:{ atk:10, def:10, spd:0, hp:10, mp:10, crit:5, dodge:0 },
    passive:'己方全队ATK+10%',
    skill:{ name:'王之号令', type:'active', target:'all_allies', effect:'全队ATK+15% 2回合(可叠加)', mpCost:20, desc:'统御之力' },
    description:'统御之力' },

  // ═══════ 以太 (4) ═══════
  { id:'分身', element:'以太', level:'SR',
    promptZh:'魔法分身', promptEn:'magic clone',
    stats:{ atk:5, def:3, spd:10, hp:5, mp:15, crit:5, dodge:10 },
    skill:{ name:'分身术', type:'active', target:'self', effect:'创造分身承受下次伤害(HP=25%)', mpCost:25, desc:'魔力凝聚的分身' },
    description:'魔力凝聚的分身' },
  { id:'不死', element:'以太', level:'SSR',
    promptZh:'不死之身', promptEn:'undying body',
    stats:{ atk:5, def:10, spd:-5, hp:40, mp:15, crit:0, dodge:0 },
    passive:'首次致死时保留1HP（每场一次）',
    skill:{ name:'死灵复苏', type:'active', target:'self', effect:'回复自身50%HP·清除负面', mpCost:25, desc:'不死之力涌动' },
    description:'拒绝死亡的意志' },
  { id:'龙神血脉', element:'以太', level:'UR',
    promptZh:'龙神之血', promptEn:'dragon god blood',
    stats:{ atk:25, def:20, spd:15, hp:50, mp:30, crit:15, dodge:5 },
    passive:'龙系免伤+20%',
    skill:{ name:'龙神咆哮', type:'active', target:'all_enemies', effect:'ATK×3.5全体+灼烧3回合', mpCost:45, multiplier:3.5, statusEffect:'burn', desc:'龙神之力释放' },
    description:'传说中龙神的后裔' },
  { id:'巨龙血脉', element:'以太', level:'SR',
    promptZh:'巨龙血脉', promptEn:'dragon bloodline',
    stats:{ atk:15, def:10, spd:5, hp:25, mp:15, crit:8, dodge:0 },
    passive:'龙系免伤+10%',
    skill:{ name:'龙息', type:'active', target:'all_enemies', effect:'ATK×2.5全体+灼烧', mpCost:30, multiplier:2.5, statusEffect:'burn', desc:'龙族吐息' },
    description:'远古巨龙的血脉传承' },

  // ═══════ 暗系扩展（原fate/magic的暗因子）═══════
  { id:'毒', element:'暗', level:'R',
    promptZh:'毒素', promptEn:'toxin',
    stats:{ atk:5, def:0, spd:0, hp:-3, mp:5, crit:3, dodge:0 },
    passive:'普通攻击附带中毒(-3%HP/回合)',
    description:'危险的毒素' },
  { id:'诅咒', element:'暗', level:'N',
    promptZh:'诅咒术', promptEn:'curse magic',
    stats:{ atk:2, def:0, spd:-2, hp:3, mp:7, crit:3, dodge:0 },
    skill:{ name:'虚弱诅咒', type:'active', target:'single_enemy', effect:'ATK-20% 2回合', mpCost:12, desc:'削弱敌方的诅咒' },
    description:'削弱敌方的诅咒' },
  { id:'诅咒之血', element:'暗', level:'R',
    promptZh:'诅咒之血', promptEn:'cursed blood',
    stats:{ atk:5, def:0, spd:3, hp:-5, mp:8, crit:5, dodge:3 },
    passive:'攻击附带减防(-5%DEF 2回合)',
    description:'流淌着被诅咒的血脉' },
  { id:'幻觉', element:'暗', level:'R',
    promptZh:'幻觉迷雾', promptEn:'illusion mist',
    stats:{ atk:0, def:2, spd:5, hp:0, mp:10, crit:0, dodge:10 },
    skill:{ name:'迷雾', type:'active', target:'all_enemies', effect:'敌全体命中-20% 2回合', mpCost:12, desc:'制造幻觉扰乱敌人' },
    description:'制造幻觉扰乱敌人' },
  { id:'深渊之印', element:'暗', level:'SR',
    promptZh:'深渊印记', promptEn:'abyssal mark',
    stats:{ atk:15, def:0, spd:-5, hp:-10, mp:18, crit:12, dodge:-5 },
    skill:{ name:'深渊凝视', type:'active', target:'single_enemy', effect:'ATK×2.0暗属性+破甲', mpCost:18, multiplier:2.0, pierceDef:0.3, desc:'深渊的凝视' },
    description:'以生命力换取深渊之力' },

  // ═══════ 地系扩展（原trait的地因子）═══════
  { id:'分裂', element:'地', level:'R',
    promptZh:'分裂增殖', promptEn:'split and multiply',
    stats:{ atk:3, def:5, spd:0, hp:8, mp:5, crit:0, dodge:2 },
    passive:'受击时15%概率分裂分身(HP=25%)',
    description:'被打散的碎片反而变多了' },
  { id:'尖刺', element:'地', level:'R',
    promptZh:'尖刺外壳', promptEn:'spiked carapace',
    stats:{ atk:5, def:8, spd:0, hp:3, mp:0, crit:2, dodge:0 },
    passive:'被攻击时反击15%伤害',
    description:'带刺的铠甲' },
  { id:'膨胀', element:'地', level:'R',
    promptZh:'膨胀鼓起的弹力身体', promptEn:'inflated bouncy body, balloon-like',
    stats:{ atk:2, def:20, spd:-4, hp:24, mp:4, crit:0, dodge:0 },
    passive:'受到伤害时反弹10%给攻击者',
    skill:{ name:'膨胀防御', type:'active', target:'self', effect:'自身DEF+25% 2回合', mpCost:12, desc:'吸入空气急剧膨胀，弹开攻击' },
    description:'吸入空气急剧膨胀，弹开攻击' },

  // ═══════ 风系扩展 ═══════
  { id:'迅捷', element:'风', level:'R',
    promptZh:'迅捷身法', promptEn:'swift movement',
    stats:{ atk:3, def:0, spd:12, hp:0, mp:0, crit:5, dodge:3 },
    description:'极快的反应速度' },
  { id:'瞬移', element:'风', level:'R',
    promptZh:'短距瞬移', promptEn:'short teleport',
    stats:{ atk:0, def:0, spd:15, hp:0, mp:8, crit:0, dodge:15 },
    skill:{ name:'瞬移闪避', type:'active', target:'self', effect:'闪避+80% 1回合', mpCost:10, desc:'瞬间移动避开攻击' },
    description:'瞬间移动避开攻击' },

  // ═══════ 神系扩展 ═══════
  { id:'王之粘液', element:'神', level:'SR',
    promptZh:'王族粘液', promptEn:'royal slime essence',
    stats:{ atk:5, def:20, spd:-5, hp:30, mp:10, crit:3, dodge:0 },
    passive:'敌方全体ATK-15%',
    skill:{ name:'王威震击', type:'active', target:'all_enemies', effect:'DEF×1.5全体', mpCost:20, multiplier:1.5, defBased:true, desc:'王族威压' },
    description:'史莱姆王族的金色粘液' },
];

// ============ 融合因子 ============
export const FUSION_FACTORS: FactorDef[] = [
  { id:'蒸汽', element:'风', subElements:['火','水'], level:'SR',
    promptZh:'蒸汽爆发,白雾弥漫', promptEn:'billowing steam, mist and heat',
    stats:{ atk:15, def:3, spd:8, hp:5, mp:15, crit:3, dodge:2 },
    skill:{ name:'蒸汽爆发', type:'active', target:'all_enemies', effect:'ATK×1.8全体', mpCost:20, multiplier:1.8, desc:'火+水碰撞产生的蒸汽之力' },
    description:'火+水碰撞产生的蒸汽之力' },
  { id:'融毁', element:'以太', subElements:['火','水'], level:'SR',
    promptZh:'融毁之力,冰火交织', promptEn:'thermal shock, melting reality',
    stats:{ atk:18, def:0, spd:5, hp:0, mp:12, crit:8, dodge:0 },
    skill:{ name:'融毁射线', type:'active', target:'single_enemy', effect:'无视30%防御', mpCost:18, multiplier:2.0, desc:'火+冰碰撞产生的融毁' },
    description:'火+冰碰撞产生的融毁' },
  { id:'雷暴', element:'风', subElements:['风','水'], level:'R',
    promptZh:'雷暴降临', promptEn:'thunderstorm',
    stats:{ atk:12, def:0, spd:6, hp:0, mp:10, crit:6, dodge:0 },
    skill:{ name:'雷暴', type:'active', target:'single_enemy', effect:'ATK×1.6+麻痹', mpCost:14, multiplier:1.6, statusEffect:'stun', desc:'雷+水引发的雷暴' },
    description:'雷+水引发的雷暴' },
  { id:'沙暴', element:'地', subElements:['地','风'], level:'R',
    promptZh:'沙暴席卷', promptEn:'sandstorm',
    stats:{ atk:10, def:5, spd:5, hp:0, mp:5, crit:3, dodge:5 },
    skill:{ name:'沙暴', type:'active', target:'all_enemies', effect:'敌方全队命中-20% 2回合', mpCost:15, desc:'地+风卷起的沙暴' },
    description:'地+风卷起的沙暴' },
  { id:'熔岩', element:'地', subElements:['火','地'], level:'R',
    promptZh:'熔岩之力', promptEn:'molten lava power',
    stats:{ atk:14, def:8, spd:-3, hp:5, mp:5, crit:3, dodge:0 },
    passive:'高攻高防低速',
    description:'火+地凝结的熔岩之力' },
  { id:'霜冻', element:'水', subElements:['水','水'], level:'R',
    promptZh:'霜冻之触', promptEn:'frost touch',
    stats:{ atk:5, def:8, spd:-3, hp:8, mp:8, crit:3, dodge:0 },
    skill:{ name:'冰冻', type:'active', target:'single_enemy', effect:'单体禁锢1回合', mpCost:16, desc:'冰+水凝结的霜冻' },
    description:'冰+水凝结的霜冻' },
  { id:'疾风', element:'风', subElements:['人','人'], level:'R',
    promptZh:'疾风迅雷', promptEn:'gale force',
    stats:{ atk:8, def:0, spd:15, hp:0, mp:0, crit:5, dodge:5 },
    passive:'先制概率+30%',
    description:'猛攻+游击融合的极致速度' },
  { id:'狱火', element:'火', subElements:['火','火'], level:'SR',
    promptZh:'地狱魔火化为烈焰风暴', promptEn:'purgatory firestorm, hellish blaze',
    stats:{ atk:38, def:6, spd:10, hp:15, mp:22, crit:15, dodge:0 },
    skill:{ name:'狱火风暴', type:'active', target:'all_enemies', effect:'ATK×2.5全体', mpCost:25, multiplier:2.5, desc:'地狱之火凝为风暴' },
    description:'地狱之火凝为风暴' },

  // 火系元素碰撞 (火+暗→? / 火+风→?)
  { id:'黑焰', element:'暗', subElements:['火','暗'], level:'SR',
    promptZh:'漆黑魔焰吞噬一切', promptEn:'black flame, devouring fire',
    stats:{ atk:35, def:4, spd:8, hp:10, mp:20, crit:18, dodge:5 },
    skill:{ name:'黑焰吞噬', type:'active', target:'single_enemy', effect:'ATK×2.5单体·吸20%HP', mpCost:22, multiplier:2.5, desc:'火+暗融合的黑焰，吞噬生命' },
    description:'火+暗融合的黑焰' },
  { id:'焰岚', element:'火', subElements:['火','风'], level:'SR',
    promptZh:'焰岚风暴席卷万物', promptEn:'blazing gale, inferno tempest',
    stats:{ atk:32, def:2, spd:18, hp:8, mp:18, crit:12, dodge:8 },
    skill:{ name:'焰岚风暴', type:'active', target:'all_enemies', effect:'ATK×2.0全体+灼烧', mpCost:24, multiplier:2.0, statusEffect:'burn', desc:'火借风势，席卷全场' },
    description:'火借风势的毁灭风暴' },

  // 三元素+融合
  { id:'极光', element:'光', subElements:['光','水','风'], level:'SSR',
    promptZh:'极光帷幕笼罩天穹', promptEn:'aurora veil, celestial light',
    stats:{ atk:20, def:20, spd:20, hp:30, mp:35, crit:10, dodge:10 },
    skill:{ name:'极光帷幕', type:'active', target:'all_allies', effect:'全队回复·ATK×3.0+3回合递增回复', mpCost:35, multiplier:3.0, desc:'极光降下，治愈万物' },
    description:'光+水+风交汇的天穹奇迹' },

  // 二元素非冲突碰撞
  { id:'藤蔓', element:'地', subElements:['地','水'], level:'R',
    promptZh:'藤蔓缠绕', promptEn:'thorny vines, grasping plants',
    stats:{ atk:5, def:6, spd:3, hp:10, mp:8, crit:2, dodge:2 },
    skill:{ name:'藤蔓缠绕', type:'active', target:'single_enemy', effect:'禁锢1回合+每回合扣HP', mpCost:15, statusEffect:'freeze', desc:'地与水催生的蔓藤' },
    description:'地与水催生的蔓藤' },
  { id:'珊瑚', element:'水', subElements:['水','光'], level:'R',
    promptZh:'珊瑚礁群', promptEn:'coral reef, living stone',
    stats:{ atk:3, def:12, spd:-2, hp:15, mp:8, crit:0, dodge:0 },
    passive:'每回合回复自身3%HP',
    description:'水与光孕育的珊瑚礁' },
  { id:'月蚀', element:'暗', subElements:['暗','光'], level:'SR',
    promptZh:'月蚀之力', promptEn:'lunar eclipse power',
    stats:{ atk:25, def:8, spd:12, hp:15, mp:22, crit:18, dodge:8 },
    skill:{ name:'月蚀', type:'active', target:'single_enemy', effect:'ATK×2.5单体·偷取1项增益', mpCost:25, multiplier:2.5, desc:'暗影吞噬光芒' },
    description:'暗影吞噬光芒' },
  { id:'雷鸣', element:'风', subElements:['风','光'], level:'SR',
    promptZh:'圣光雷鸣', promptEn:'holy thunder, radiant storm',
    stats:{ atk:30, def:5, spd:20, hp:12, mp:18, crit:22, dodge:8 },
    skill:{ name:'圣雷', type:'active', target:'single_enemy', effect:'ATK×2.5单体·必暴+破甲', mpCost:26, multiplier:2.5, pierceDef:0.3, desc:'光与风交织的制裁之雷' },
    description:'光与风交织的制裁之雷' },
  // 膨胀系列融合
  { id:'气球', element:'风', subElements:['地','风'], level:'R',
    promptZh:'气球炸弹飘浮', promptEn:'balloon bomb, floating explosive',
    stats:{ atk:8, def:12, spd:8, hp:18, mp:5, crit:2, dodge:5 },
    skill:{ name:'气球炸弹', type:'active', target:'single_enemy', effect:'DEF×1.5自爆式攻击', mpCost:14, multiplier:1.5, defBased:true, desc:'膨胀到极限后炸向敌人' },
    description:'膨胀+风, 膨胀到极限后炸向敌人' },
  { id:'毒云', element:'暗', subElements:['地','暗'], level:'R',
    promptZh:'毒云弥漫', promptEn:'toxic cloud, poisonous miasma',
    stats:{ atk:10, def:6, spd:2, hp:10, mp:10, crit:4, dodge:2 },
    skill:{ name:'毒云扩散', type:'active', target:'all_enemies', effect:'全体中毒(-3%HP×3回合)', mpCost:18, desc:'毒液汽化弥漫全场' },
    description:'膨胀+毒, 毒液汽化弥漫全场' },
];

// ============ 所有因子字典 ============
export const ALL_FACTORS: Record<string, FactorDef> = {};
[...BASE_FACTORS, ...FUSION_FACTORS].forEach(f => { ALL_FACTORS[f.id] = f; });

// ============ 冲突融合规则 ============
export const CONFLICT_FUSIONS: ConflictFusionRule[] = [
  { inputs: ['火','水'], output:'蒸汽', level:'SR' },
  { inputs: ['火','冰'], output:'融毁', level:'SR' },
  { inputs: ['雷','水'], output:'雷暴', level:'R'  },
  { inputs: ['地','风'], output:'沙暴', level:'R'  },
  { inputs: ['火','地'], output:'熔岩', level:'R'  },
  { inputs: ['冰','水'], output:'霜冻', level:'R'  },
  { inputs: ['猛攻','游击'], output:'疾风', level:'R' },
  { inputs: ['火','暗'], output:'黑焰', level:'SR' },
  { inputs: ['火','风'], output:'焰岚', level:'SR' },
  { inputs: ['地','水'], output:'藤蔓', level:'R' },
  { inputs: ['水','光'], output:'珊瑚', level:'R' },
  { inputs: ['暗','光'], output:'月蚀', level:'SR' },
  { inputs: ['风','光'], output:'雷鸣', level:'SR' },
  { inputs: ['膨胀','风'], output:'气球', level:'R' },
  { inputs: ['膨胀','毒'], output:'毒云', level:'R' },
];

// ============ 共鸣规则（仅跨元素）============
export const RESONANCES: ResonanceRule[] = [
  { name:'深渊潮汐', title:'深渊使者', requiredAtoms:['水','暗'], tag:'water', minCount:2, bonus:'敌方每回合减DEF 5%' },
  { name:'炎岚圣光', title:'炎岚', requiredAtoms:['火','风','光'], tag:'fire', minCount:2, bonus:'全队每回合回HP 2%' },
  { name:'大地之盾', title:'地卫', requiredAtoms:['地','人'], tag:'earth', minCount:2, bonus:'全队受物理伤害-10%' },
  { name:'神罚', title:'神罚者', requiredAtoms:['神','光'], tag:'light', minCount:2, bonus:'对暗元素目标暴击率+20%' },
  { name:'混沌共鸣', title:'混沌', requiredAtoms:['地','火','水','风'], tag:'fire', minCount:1, bonus:'全队发展度+1' },
  { name:'虚空低语', title:'虚空行者', requiredAtoms:['以太','暗'], tag:'dark', minCount:2, bonus:'每回合随机一个敌方因子失效' },
  { name:'生命轮回', title:'轮回', requiredAtoms:['水','风','地'], tag:'water', minCount:2, bonus:'被击败时30%概率保留1HP' },
];

// ============ 升星可选因子池 ============
export const STAR_FACTOR_POOLS: Record<number, string[]> = {
  2: ['地','火','水','冰','风','雷','光','暗',
    '猛攻','精准','守护','游击','治愈','诅咒'],
  3: ['岩石','烈焰','激流','极寒','暴风','雷霆','圣光','暗影',
    '反击','坚韧','分裂','尖刺','膨胀','迅捷','增幅','毒','诅咒之血','幻觉','瞬移',
    '雷暴','沙暴','熔岩','霜冻','疾风','藤蔓','珊瑚'],
  4: ['山岳','爆炎','深渊','玄冰','飓风','劫雷','神辉','冥暗',
    '咆哮','结界','王之力','王之粘液','巨龙血脉','分身','深渊之印',
    '蒸汽','融毁','狱火','黑焰','焰岚','月蚀','雷鸣'],
  5: ['地核','阳炎','沧溟','永冻','虚空风','天罚','天光','虚无',
    '不死','极光','殉道*','黄昏*'],
  6: ['星核','凤凰火','归墟','绝对零度','时空风暴','混沌雷','创世之光','湮灭','龙神血脉'],
};
