// ============================================
// 魔女卡牌 — 因子配置（32 基础 + 12 融合 = 44 全部可获取）
// 原则：写的每个因子都能在游戏中获得
// ============================================
import type { FactorDef, ConflictFusionRule, ResonanceRule } from '../types';

// ============ 基础因子 ============
export const BASE_FACTORS: FactorDef[] = [
  // 🔥 元素系 (8)
  { id:'火', category:'element', level:'N', tag:'fire',
    promptZh:'火焰环绕,赤红魔力', promptEn:'flame aura, crimson magic',
    stats:{ atk:8, def:0, spd:3, hp:0, mp:8, crit:2, dodge:0 },
    description:'基础火元素' },
  { id:'水', category:'element', level:'N', tag:'water',
    promptZh:'水流环绕,碧蓝魔力', promptEn:'water aura, azure magic',
    stats:{ atk:3, def:3, spd:0, hp:8, mp:8, crit:1, dodge:1 },
    description:'基础水元素' },
  { id:'风', category:'element', level:'N', tag:'wind',
    promptZh:'疾风环绕,翠绿魔力', promptEn:'wind aura, emerald magic',
    stats:{ atk:5, def:0, spd:8, hp:0, mp:5, crit:3, dodge:2 },
    description:'基础风元素' },
  { id:'雷', category:'element', level:'N', tag:'thunder',
    promptZh:'雷光闪烁,金黄魔力', promptEn:'thunder sparks, golden magic',
    stats:{ atk:10, def:0, spd:5, hp:0, mp:3, crit:5, dodge:0 },
    description:'基础雷元素' },
  { id:'冰', category:'element', level:'N', tag:'ice',
    promptZh:'冰晶凝结,浅蓝魔力', promptEn:'ice crystals, pale blue magic',
    stats:{ atk:4, def:6, spd:-2, hp:4, mp:6, crit:2, dodge:0 },
    description:'基础冰元素' },
  { id:'暗', category:'element', level:'N', tag:'dark',
    promptZh:'暗影弥漫,紫黑魔力', promptEn:'shadow aura, dark purple magic',
    stats:{ atk:7, def:0, spd:4, hp:0, mp:7, crit:4, dodge:1 },
    description:'基础暗元素' },
  { id:'光', category:'element', level:'N', tag:'light',
    promptZh:'柔光普照,金色魔力', promptEn:'gentle light, golden magic',
    stats:{ atk:0, def:5, spd:2, hp:6, mp:6, crit:0, dodge:0 },
    passive:'回合结束回复 3% HP',
    description:'基础光元素' },
  { id:'地', category:'element', level:'N', tag:'earth',
    promptZh:'大地之力,厚重魔力', promptEn:'earth power, heavy magic',
    stats:{ atk:0, def:10, spd:-5, hp:10, mp:2, crit:0, dodge:0 },
    description:'基础地元素' },

  // 🔥 元素系 R级 (8) — 6×N→R堆叠产物
  { id:'烈焰', category:'element', level:'R', tag:'fire',
    promptZh:'烈焰爆发,灼热难耐', promptEn:'blazing eruption, searing heat',
    stats:{ atk:22, def:3, spd:6, hp:5, mp:14, crit:8, dodge:0 },
    skill:{ name:'爆裂火球', type:'active', target:'single_enemy', effect:'ATK×1.8+灼烧2回合', mpCost:15, multiplier:1.8, statusEffect:'burn', desc:'压缩火焰爆裂，附加灼烧' },
    description:'高密度火焰的压缩体，蕴含爆发之力' },
  { id:'激流', category:'element', level:'R', tag:'water',
    promptZh:'激流奔涌,碧蓝狂潮', promptEn:'raging torrent, azure surge',
    stats:{ atk:10, def:8, spd:8, hp:12, mp:14, crit:3, dodge:3 },
    skill:{ name:'水龙卷', type:'active', target:'all_enemies', effect:'ATK×1.5全体', mpCost:18, multiplier:1.5, desc:'激流化为水龙卷，冲击全体敌人' },
    description:'奔涌不息的激流，势不可挡' },
  { id:'暴风', category:'element', level:'R', tag:'wind',
    promptZh:'暴风怒号,翠绿风暴', promptEn:'howling gale, emerald tempest',
    stats:{ atk:14, def:2, spd:22, hp:4, mp:10, crit:10, dodge:12 },
    skill:{ name:'风刃乱舞', type:'active', target:'random_enemy', effect:'3连击·ATK×0.8', mpCost:14, multiplier:0.8, hits:3, desc:'暴风化为利刃，三连斩击随机目标' },
    description:'撕裂大气的风暴，无孔不入' },
  { id:'雷霆', category:'element', level:'R', tag:'thunder',
    promptZh:'雷霆万钧,雷光炸裂', promptEn:'thundering might, lightning burst',
    stats:{ atk:26, def:0, spd:14, hp:3, mp:12, crit:18, dodge:0 },
    skill:{ name:'天雷击', type:'active', target:'single_enemy', effect:'ATK×2.2+30%眩晕', mpCost:20, multiplier:2.2, statusEffect:'stun', desc:'召唤天雷劈下，高暴击+眩晕' },
    description:'天穹降下的雷霆，一击万钧' },
  { id:'极寒', category:'element', level:'R', tag:'ice',
    promptZh:'极寒冰狱,绝对零度', promptEn:'frozen prison, absolute zero',
    stats:{ atk:6, def:18, spd:0, hp:16, mp:12, crit:3, dodge:0 },
    skill:{ name:'冰封结界', type:'active', target:'all_enemies', effect:'DEF×2.0全体+自身DEF+10', mpCost:18, multiplier:2.0, defBased:true, desc:'极寒结界冻结全场，提升自身防御' },
    description:'绝对零度的寒气，封印万物' },
  { id:'暗影', category:'element', level:'R', tag:'dark',
    promptZh:'暗影深渊,黑幕笼罩', promptEn:'abyssal shadow, dark shroud',
    stats:{ atk:18, def:4, spd:10, hp:6, mp:12, crit:14, dodge:5 },
    skill:{ name:'暗影突刺', type:'active', target:'single_enemy', effect:'ATK×2.0·无视50%防御', mpCost:17, multiplier:2.0, pierceDef:0.5, desc:'从阴影中刺出致命一击，穿透防御' },
    description:'深渊暗影的化身，刺穿一切防御' },
  { id:'圣光', category:'element', level:'R', tag:'light',
    promptZh:'圣光降临,金色庇护', promptEn:'holy light descends, golden blessing',
    stats:{ atk:4, def:10, spd:6, hp:16, mp:20, crit:0, dodge:0 },
    skill:{ name:'光之守护', type:'active', target:'all_allies', effect:'回复ATK×2.0+全体DEF+5·2回合', mpCost:16, multiplier:2.0, heal:true, desc:'圣光笼罩全员，回复生命并提升防御' },
    description:'纯净圣光，庇护与治愈之力' },
  { id:'岩石', category:'element', level:'R', tag:'earth',
    promptZh:'岩石堡垒,大地脉动', promptEn:'stone bastion, earth pulse',
    stats:{ atk:4, def:22, spd:-5, hp:28, mp:5, crit:2, dodge:0 },
    skill:{ name:'地裂', type:'active', target:'all_enemies', effect:'DEF×2.0全体', mpCost:20, multiplier:2.0, defBased:true, desc:'撕裂大地，以防御力碾压全体敌人' },
    description:'大地脉动的岩石结晶，固若金汤' },

  // 🔥 元素系 SR/SSR/UR (24) — 高阶堆叠产物
  { id:'阳炎', category:'element', level:'SSR', tag:'fire',
    promptZh:'太阳表面之火，焚烧万物', promptEn:'solar flame, miniature sun',
    stats:{ atk:65, def:10, spd:16, hp:30, mp:35, crit:26, dodge:0 },
    skill:{ name:'太阳火', type:'active', target:'single_enemy', effect:'ATK×3.2单体·无视50%防', mpCost:30, multiplier:3.2, desc:'太阳之火凝为一点，贯穿一切防御', pierceDef:0.5 },
    description:'太阳之火凝为一点，贯穿一切防御' },
  { id:'凤凰火', category:'element', level:'UR', tag:'fire',
    promptZh:'不死鸟涅槃重生，烈焰焚天', promptEn:'phoenix rebirth, divine flame',
    stats:{ atk:110, def:18, spd:24, hp:55, mp:50, crit:38, dodge:5 },
    passive:'死亡后以50%HP复活1次',
    skill:{ name:'涅槃', type:'active', target:'all_enemies', effect:'ATK×4.0全体+死亡后复活50%HP', mpCost:50, multiplier:4.0, desc:'凤凰涅槃，燃尽后重生' },
    description:'凤凰涅槃，燃尽后重生' },
  { id:'深渊', category:'element', level:'SR', tag:'water',
    promptZh:'深渊暗流吞噬一切', promptEn:'abyssal maelstrom, deep vortex',
    stats:{ atk:18, def:14, spd:12, hp:25, mp:22, crit:6, dodge:5 },
    skill:{ name:'深渊漩涡', type:'active', target:'all_enemies', effect:'ATK×2.2全体+减速2回合', mpCost:28, multiplier:2.2, desc:'来自无尽深渊的吞噬漩涡', statusEffect:'slow' },
    description:'来自无尽深渊的吞噬漩涡' },
  { id:'沧溟', category:'element', level:'SSR', tag:'water',
    promptZh:'沧溟之海吞噬大地', promptEn:'vast ocean tidal wave',
    stats:{ atk:30, def:22, spd:18, hp:45, mp:35, crit:10, dodge:8 },
    skill:{ name:'沧溟潮汐', type:'active', target:'all_enemies', effect:'ATK×3.0全体·回复自身30%HP', mpCost:38, multiplier:3.0, desc:'沧溟之力化为吞噬一切的潮汐', heal:true },
    description:'沧溟之力化为吞噬一切的潮汐' },
  { id:'归墟', category:'element', level:'UR', tag:'water',
    promptZh:'万物归墟，归于虚无', promptEn:'return to void, cosmic ocean',
    stats:{ atk:50, def:35, spd:25, hp:80, mp:50, crit:15, dodge:12 },
    passive:'受到伤害的15%反弹给攻击者',
    skill:{ name:'归墟', type:'active', target:'all_enemies', effect:'ATK×3.5全体·敌全体DEF-20%', mpCost:50, multiplier:3.5, desc:'万物终将归于虚无之海', statusEffect:'def_down' },
    description:'万物终将归于虚无之海' },
  { id:'飓风', category:'element', level:'SR', tag:'wind',
    promptZh:'飓风之眼割裂一切', promptEn:'hurricane eye, tornado',
    stats:{ atk:25, def:4, spd:35, hp:10, mp:15, crit:18, dodge:18 },
    skill:{ name:'飓风之眼', type:'active', target:'random_enemy', effect:'5连击·ATK×0.6随机目标', mpCost:25, multiplier:0.6, desc:'暴风之核，五道风刃割裂战场', hits:5 },
    description:'暴风之核，五道风刃割裂战场' },
  { id:'虚空风', category:'element', level:'SSR', tag:'wind',
    promptZh:'虚空裂隙撕裂时空', promptEn:'void gale, dimensional tear',
    stats:{ atk:45, def:8, spd:50, hp:20, mp:25, crit:28, dodge:25 },
    skill:{ name:'虚空裂隙', type:'active', target:'random_enemy', effect:'8连击·ATK×0.5随机+穿透', mpCost:35, multiplier:0.5, desc:'风在虚空中撕开裂隙，无物不破', hits:8, pierceDef:0.3 },
    description:'风在虚空中撕开裂隙，无物不破' },
  { id:'时空风暴', category:'element', level:'UR', tag:'wind',
    promptZh:'时空风暴碾碎维度', promptEn:'spacetime storm, temporal collapse',
    stats:{ atk:75, def:14, spd:70, hp:38, mp:38, crit:38, dodge:35 },
    passive:'基础行动速度+30%',
    skill:{ name:'时空崩坏', type:'active', target:'random_enemy', effect:'10连击·ATK×0.5随机+时停2回合', mpCost:50, multiplier:0.5, desc:'扭曲时空的风暴，令时间也为止停滞', hits:10, statusEffect:'freeze' },
    description:'扭曲时空的风暴，令时间也为止停滞' },
  { id:'劫雷', category:'element', level:'SR', tag:'thunder',
    promptZh:'天劫之雷直劈而下', promptEn:'calamity lightning, divine bolt',
    stats:{ atk:45, def:2, spd:22, hp:8, mp:18, crit:28, dodge:0 },
    skill:{ name:'劫雷', type:'active', target:'single_enemy', effect:'ATK×3.0单体·40%眩晕', mpCost:28, multiplier:3.0, desc:'天劫之雷，一击必杀', statusEffect:'stun' },
    description:'天劫之雷，一击必杀' },
  { id:'天罚', category:'element', level:'SSR', tag:'thunder',
    promptZh:'天罚神雷降世', promptEn:'divine punishment, heaven bolt',
    stats:{ atk:78, def:5, spd:30, hp:18, mp:28, crit:40, dodge:0 },
    skill:{ name:'天罚', type:'active', target:'single_enemy', effect:'ATK×3.8单体·必暴+50%眩晕', mpCost:38, multiplier:3.8, desc:'天降神罚之雷，无人能挡', statusEffect:'stun' },
    description:'天降神罚之雷，无人能挡' },
  { id:'混沌雷', category:'element', level:'UR', tag:'thunder',
    promptZh:'混沌初开雷霆万钧', promptEn:'primordial chaos lightning',
    stats:{ atk:130, def:10, spd:38, hp:35, mp:42, crit:55, dodge:0 },
    passive:'暴击伤害+50%',
    skill:{ name:'混沌雷暴', type:'active', target:'single_enemy', effect:'ATK×5.0单体·无视防御·必暴', mpCost:55, multiplier:5.0, desc:'混沌初开时诞生的原始雷电', pierceDef:1.0 },
    description:'混沌初开时诞生的原始雷电' },
  { id:'玄冰', category:'element', level:'SR', tag:'ice',
    promptZh:'千年玄冰化为壁障', promptEn:'black ice, ancient frost',
    stats:{ atk:10, def:28, spd:2, hp:28, mp:18, crit:5, dodge:0 },
    skill:{ name:'玄冰壁障', type:'active', target:'all_enemies', effect:'DEF×2.5全体+全体DEF+10', mpCost:28, multiplier:2.5, desc:'千年玄冰凝成的壁障，坚不可摧', defBased:true },
    description:'千年玄冰凝成的壁障，坚不可摧' },
  { id:'永冻', category:'element', level:'SSR', tag:'ice',
    promptZh:'永冻冰狱封绝万物', promptEn:'eternal frost, frozen hell',
    stats:{ atk:18, def:42, spd:4, hp:48, mp:28, crit:8, dodge:0 },
    skill:{ name:'永冻冰狱', type:'active', target:'all_enemies', effect:'DEF×3.2全体·敌全体冻结1回合', mpCost:38, multiplier:3.2, desc:'永恒冰封的地狱，连时间也为之冻结', defBased:true, statusEffect:'freeze' },
    description:'永恒冰封的地狱，连时间也为之冻结' },
  { id:'绝对零度', category:'element', level:'UR', tag:'ice',
    promptZh:'绝对零度封绝宇宙', promptEn:'absolute zero, cosmic cold',
    stats:{ atk:30, def:60, spd:6, hp:85, mp:40, crit:12, dodge:0 },
    passive:'受到物理伤害-25%',
    skill:{ name:'绝对零度', type:'active', target:'all_enemies', effect:'DEF×4.5全体·冻结+破甲', mpCost:55, multiplier:4.5, desc:'绝对零度的寒气，冻结一切存在', defBased:true, statusEffect:'freeze' },
    description:'绝对零度的寒气，冻结一切存在' },
  { id:'冥暗', category:'element', level:'SR', tag:'dark',
    promptZh:'冥界暗影吞噬生命', promptEn:'underworld darkness, soul eater',
    stats:{ atk:32, def:7, spd:16, hp:12, mp:18, crit:22, dodge:8 },
    skill:{ name:'冥暗吞噬', type:'active', target:'single_enemy', effect:'ATK×2.5单体·吸收30%伤害为HP', mpCost:26, multiplier:2.5, desc:'冥界深渊的影子，吞噬生命之力', pierceDef:0.5 },
    description:'冥界深渊的影子，吞噬生命之力' },
  { id:'虚无', category:'element', level:'SSR', tag:'dark',
    promptZh:'虚无之力湮灭一切', promptEn:'void obliteration, nothingness',
    stats:{ atk:55, def:12, spd:24, hp:25, mp:28, crit:32, dodge:14 },
    skill:{ name:'虚无湮灭', type:'active', target:'single_enemy', effect:'ATK×3.5单体·无视80%防', mpCost:38, multiplier:3.5, desc:'虚无之力，将存在抹去', pierceDef:0.8 },
    description:'虚无之力，将存在抹去' },
  { id:'湮灭', category:'element', level:'UR', tag:'dark',
    promptZh:'彻底湮灭不复存在', promptEn:'annihilation, erasure from existence',
    stats:{ atk:95, def:20, spd:34, hp:48, mp:42, crit:45, dodge:20 },
    passive:'击杀回复自身30%HP',
    skill:{ name:'湮灭', type:'active', target:'single_enemy', effect:'ATK×5.0单体·即死20%概率', mpCost:55, multiplier:5.0, desc:'将目标从存在中彻底抹去', pierceDef:1.0, statusEffect:'instant_kill' },
    description:'将目标从存在中彻底抹去' },
  { id:'神辉', category:'element', level:'SR', tag:'light',
    promptZh:'神之光辉驱散一切诅咒', promptEn:'divine radiance, holy blessing',
    stats:{ atk:8, def:16, spd:10, hp:28, mp:30, crit:2, dodge:0 },
    skill:{ name:'神辉祝福', type:'active', target:'all_allies', effect:'回复全体HP·ATK×3.0+清除debuff', mpCost:28, multiplier:3.0, desc:'神辉普照，净化与治愈一切', heal:true },
    description:'神辉普照，净化与治愈一切' },
  { id:'天光', category:'element', level:'SSR', tag:'light',
    promptZh:'天堂之光照耀众生', promptEn:'heavenly light, divine grace',
    stats:{ atk:14, def:24, spd:15, hp:48, mp:42, crit:4, dodge:2 },
    skill:{ name:'天光', type:'active', target:'all_allies', effect:'回复全体·ATK×4.0+全体DEF+15', mpCost:40, multiplier:4.0, desc:'天堂之光，治愈与守护并存', heal:true },
    description:'天堂之光，治愈与守护并存' },
  { id:'创世之光', category:'element', level:'UR', tag:'light',
    promptZh:'创世之初的第一道光', promptEn:'creation light, genesis',
    stats:{ atk:24, def:36, spd:22, hp:85, mp:58, crit:8, dodge:5 },
    passive:'回合结束回复全体5%HP',
    skill:{ name:'创世之光', type:'active', target:'all_allies', effect:'复活1队友+全体回复+3回合递增回复', mpCost:65, multiplier:5.0, desc:'创世之初的光芒，孕育万物之生机', heal:true },
    description:'创世之初的光芒，孕育万物之生机' },
  { id:'山岳', category:'element', level:'SR', tag:'earth',
    promptZh:'山岳崩塌之力', promptEn:'mountain collapse, landslide',
    stats:{ atk:8, def:35, spd:-6, hp:48, mp:8, crit:4, dodge:0 },
    skill:{ name:'山崩', type:'active', target:'all_enemies', effect:'DEF×3.0全体', mpCost:28, multiplier:3.0, desc:'山岳崩塌，大地怒吼', defBased:true },
    description:'山岳崩塌，大地怒吼' },
  { id:'地核', category:'element', level:'SSR', tag:'earth',
    promptZh:'地核爆裂撼动大地', promptEn:'planetary core eruption',
    stats:{ atk:14, def:52, spd:-8, hp:80, mp:14, crit:6, dodge:0 },
    skill:{ name:'地核爆裂', type:'active', target:'all_enemies', effect:'DEF×3.8全体+敌全体SPD-15', mpCost:40, multiplier:3.8, desc:'地核之力喷涌而出，撼动一切', defBased:true },
    description:'地核之力喷涌而出，撼动一切' },
  { id:'星核', category:'element', level:'UR', tag:'earth',
    promptZh:'星球之核重力碾压', promptEn:'planetary core, gravity crush',
    stats:{ atk:24, def:75, spd:-10, hp:140, mp:22, crit:10, dodge:0 },
    passive:'受到的物理伤害-30%',
    skill:{ name:'星核重压', type:'active', target:'all_enemies', effect:'DEF×5.0全体+全体眩晕1回合', mpCost:55, multiplier:5.0, desc:'星球之核的引力碾碎一切', defBased:true, statusEffect:'stun' },
    description:'星球之核的引力碾碎一切' },


  // ⚔️ 战斗系 (5)
  { id:'猛攻', category:'combat', level:'N',
    promptZh:'猛攻之势', promptEn:'aggressive stance',
    stats:{ atk:10, def:-3, spd:2, hp:0, mp:0, crit:3, dodge:-1 },
    description:'牺牲防御换取高攻' },
  { id:'精准', category:'combat', level:'N',
    promptZh:'精准打击', promptEn:'precise strike',
    stats:{ atk:5, def:0, spd:3, hp:2, mp:0, crit:8, dodge:0 },
    description:'高暴击，稳定输出' },
  { id:'守护', category:'combat', level:'N',
    promptZh:'守护之盾', promptEn:'guardian shield',
    stats:{ atk:-3, def:12, spd:-2, hp:8, mp:0, crit:0, dodge:0 },
    description:'高防御，适合前排' },
  { id:'游击', category:'combat', level:'N',
    promptZh:'游击战术', promptEn:'hit and run tactics',
    stats:{ atk:6, def:-5, spd:10, hp:0, mp:0, crit:2, dodge:5 },
    description:'高闪避，高速游击' },
  { id:'献祭', category:'combat', level:'N',
    promptZh:'献祭之身', promptEn:'sacrificial body',
    stats:{ atk:8, def:-8, spd:3, hp:-5, mp:5, crit:5, dodge:0 },
    passive:'死亡时全队回复 HP 30%',
    description:'死后爆发的孤注一掷' },

  // 🧬 特质系 (5)
  { id:'粘液', category:'trait', level:'N', tag:'slime',
    promptZh:'粘液体质', promptEn:'slime body',
    stats:{ atk:0, def:5, spd:-3, hp:10, mp:0, crit:0, dodge:5 },
    description:'史莱姆的胶质身躯' },
  { id:'软体', category:'trait', level:'N', tag:'slime',
    promptZh:'软体结构', promptEn:'soft body structure',
    stats:{ atk:0, def:3, spd:2, hp:5, mp:0, crit:0, dodge:3 },
    description:'柔软的身体吸收冲击' },
  { id:'分裂', category:'trait', level:'R', tag:'slime',
    promptZh:'分裂增殖', promptEn:'split and multiply',
    stats:{ atk:3, def:5, spd:0, hp:8, mp:5, crit:0, dodge:2 },
    passive:'受击时有20%概率分裂出一个分身(HP=25%)',
    description:'被打散的粘液反而变多了' },
  { id:'尖刺', category:'trait', level:'R',
    promptZh:'尖刺外壳', promptEn:'spiked carapace',
    stats:{ atk:5, def:8, spd:0, hp:3, mp:0, crit:2, dodge:0 },
    passive:'被攻击时反击 15% 伤害',
    description:'带刺的铠甲' },
  { id:'迅捷', category:'trait', level:'R',
    promptZh:'迅捷身法', promptEn:'swift movement',
    stats:{ atk:3, def:0, spd:12, hp:0, mp:0, crit:5, dodge:3 },
    description:'极快的反应速度' },
  { id:'巨龙血脉', category:'trait', level:'SR', tag:'dragon',
    promptZh:'巨龙血脉', promptEn:'dragon bloodline',
    stats:{ atk:15, def:10, spd:5, hp:25, mp:15, crit:8, dodge:0 },
    passive:'龙系抗性 +30%',
    skill:{ name:'龙息', type:'active', target:'all_enemies', effect:'ATK×2.5全体+灼烧', mpCost:30, multiplier:2.5, desc:'龙族吐息，焚尽一切' },
    description:'远古巨龙的血脉传承' },
  { id:'王之粘液', category:'trait', level:'SR', tag:'slime',
    promptZh:'王族粘液', promptEn:'royal slime essence',
    stats:{ atk:5, def:20, spd:-5, hp:30, mp:10, crit:3, dodge:0 },
    passive:'王威: 敌方全体 ATK-15%',
    skill:{ name:'王威震击', type:'active', target:'all_enemies', effect:'DEF相关全体攻击', mpCost:20, multiplier:1.5, desc:'王族威压，镇压全场' },
    description:'史莱姆王族的金色粘液，蕴含镇压之力' },

  // ✨ 魔力系 (5)
  { id:'治愈', category:'magic', level:'N',
    promptZh:'治愈魔法', promptEn:'healing magic',
    stats:{ atk:0, def:2, spd:1, hp:5, mp:8, crit:0, dodge:0 },
    skill:{ name:'治愈术', type:'active', target:'single_ally', effect:'回复 HP', mpCost:10, multiplier:1.0, desc:'单体回复 ATK×1.0 HP' },
    description:'基础治疗魔法' },
  { id:'诅咒', category:'magic', level:'N',
    promptZh:'诅咒术', promptEn:'curse magic',
    stats:{ atk:2, def:0, spd:-2, hp:3, mp:7, crit:3, dodge:0 },
    skill:{ name:'虚弱诅咒', type:'active', target:'single_enemy', effect:'ATK -20% 2回合', mpCost:12 },
    description:'削弱敌方的诅咒' },
  { id:'召唤', category:'magic', level:'R',
    promptZh:'召唤术', promptEn:'summoning magic',
    stats:{ atk:0, def:5, spd:-3, hp:8, mp:15, crit:0, dodge:0 },
    skill:{ name:'召唤帮手', type:'active', target:'self', effect:'额外召唤物参战', mpCost:20 },
    description:'召唤一个小伙伴' },
  { id:'增幅', category:'magic', level:'R',
    promptZh:'魔力增幅', promptEn:'magic amplification',
    stats:{ atk:3, def:2, spd:2, hp:2, mp:10, crit:0, dodge:0 },
    skill:{ name:'魔力增幅', type:'active', target:'all_allies', effect:'全队 ATK+25% 2回合', mpCost:15 },
    description:'强化全队的魔力' },
  { id:'结界', category:'magic', level:'SR',
    promptZh:'魔法结界', promptEn:'magic barrier',
    stats:{ atk:0, def:15, spd:-5, hp:10, mp:20, crit:0, dodge:0 },
    skill:{ name:'魔法结界', type:'active', target:'all_allies', effect:'全队减伤 30% 2回合', mpCost:25 },
    description:'守护全队的魔法屏障' },

  // 🎭 灵魂系 (4)
  { id:'冷静', category:'soul', level:'N',
    promptZh:'冷静沉着', promptEn:'calm and collected',
    stats:{ atk:-2, def:3, spd:0, hp:2, mp:5, crit:0, dodge:3 },
    passive:'被暴击率 -10%',
    description:'不被情绪左右的冷静' },
  { id:'狂热', category:'soul', level:'N', tag:'fire',
    promptZh:'狂热战意', promptEn:'berserker frenzy',
    stats:{ atk:8, def:-5, spd:3, hp:-5, mp:0, crit:10, dodge:-5 },
    description:'以理智换取力量的狂热' },
  { id:'慈悲', category:'soul', level:'R',
    promptZh:'慈悲之心', promptEn:'merciful heart',
    stats:{ atk:-5, def:5, spd:0, hp:8, mp:8, crit:0, dodge:0 },
    passive:'治疗量 +25%',
    description:'怜悯众生的温柔' },
  { id:'慵懒', category:'soul', level:'R',
    promptZh:'慵懒随性', promptEn:'leisurely and carefree',
    stats:{ atk:-8, def:10, spd:-8, hp:15, mp:0, crit:0, dodge:8 },
    description:'懒散但防御惊人' },

  // 🌟 命运系 (5)
  { id:'星之祝福', category:'fate', level:'N',
    promptZh:'星之祝福', promptEn:'star blessing',
    stats:{ atk:2, def:2, spd:2, hp:2, mp:2, crit:2, dodge:1 },
    description:'星光的微弱祝福' },
  { id:'幸运', category:'fate', level:'N',
    promptZh:'幸运之星', promptEn:'lucky star',
    stats:{ atk:0, def:0, spd:0, hp:0, mp:0, crit:5, dodge:5 },
    passive:'暴击伤害 +10%',
    description:'被幸运女神眷顾' },
  { id:'毒', category:'fate', level:'R',
    promptZh:'毒素', promptEn:'toxin',
    stats:{ atk:5, def:0, spd:0, hp:-3, mp:5, crit:3, dodge:0 },
    passive:'攻击附带中毒(-3% HP/回合)',
    description:'危险的毒素' },
  { id:'深渊之印', category:'fate', level:'SR',
    promptZh:'深渊印记', promptEn:'abyssal mark',
    stats:{ atk:15, def:0, spd:-5, hp:-10, mp:18, crit:12, dodge:-5 },
    skill:{ name:'深渊凝视', type:'active', target:'single_enemy', effect:'ATK×2.0暗属性+恐惧1回合', mpCost:18, multiplier:2.0, desc:'深渊的凝视，动摇敌人意志' },
    description:'以生命力换取深渊之力' },
  { id:'王之力', category:'fate', level:'SR',
    promptZh:'王者之力', promptEn:'king\'s power',
    stats:{ atk:10, def:10, spd:0, hp:10, mp:10, crit:5, dodge:0 },
    skill:{ name:'王之号令', type:'aura', target:'all_allies', effect:'全队 ATK+10% 光环', mpCost:0 },
    description:'统御之力，全队光环' },

  // === 新增基础因子 (用于怪物池扩展) ===
  // 特质系 N
  { id:'硬壳', category:'trait', level:'N',
    promptZh:'坚硬甲壳', promptEn:'hard shell',
    stats:{ atk:0, def:8, spd:-3, hp:5, mp:0, crit:0, dodge:-5 },
    description:'天然甲壳护体' },
  { id:'鳞片', category:'trait', level:'N',
    promptZh:'细密鳞片', promptEn:'fine scales',
    stats:{ atk:2, def:5, spd:1, hp:3, mp:0, crit:0, dodge:2 },
    description:'鳞片护身，轻便灵活' },
  // 魔法系 N
  { id:'屏障', category:'magic', level:'N',
    promptZh:'魔法屏障', promptEn:'magic barrier',
    stats:{ atk:0, def:8, spd:0, hp:5, mp:5, crit:0, dodge:0 },
    passive:'受击时 15% 概率减伤 30%',
    description:'一层薄薄的魔力护盾' },
  { id:'闪光', category:'magic', level:'N',
    promptZh:'闪光术', promptEn:'flash spell',
    stats:{ atk:0, def:0, spd:5, hp:0, mp:8, crit:0, dodge:8 },
    description:'炫目闪光，闪避率提升' },
  // 灵魂系 N
  { id:'勇敢', category:'soul', level:'N',
    promptZh:'勇敢之心', promptEn:'brave heart',
    stats:{ atk:5, def:2, spd:2, hp:5, mp:0, crit:2, dodge:0 },
    description:'无所畏惧的精神' },
  { id:'胆怯', category:'soul', level:'N',
    promptZh:'胆小谨慎', promptEn:'timid caution',
    stats:{ atk:-3, def:3, spd:8, hp:0, mp:5, crit:0, dodge:6 },
    description:'小心使得万年船' },
  // 战斗系 R
  { id:'反击', category:'combat', level:'R',
    promptZh:'反击架势', promptEn:'counter stance',
    stats:{ atk:6, def:8, spd:-2, hp:5, mp:0, crit:0, dodge:0 },
    passive:'受击时 20% 概率反击 ATK×0.5',
    description:'以守为攻的战斗技巧' },
  { id:'坚韧', category:'combat', level:'R',
    promptZh:'坚韧不拔', promptEn:'unyielding',
    stats:{ atk:0, def:12, spd:0, hp:15, mp:0, crit:0, dodge:0 },
    passive:'HP 低于 30% 时 DEF+30%',
    description:'绝境中爆发顽强生命力' },
  { id:'毒牙', category:'trait', level:'R',
    promptZh:'剧毒獠牙', promptEn:'venomous fangs',
    stats:{ atk:8, def:0, spd:4, hp:2, mp:0, crit:2, dodge:0 },
    passive:'普通攻击附带毒伤 -3%HP 2回合',
    description:'淬毒的尖牙利齿' },
  { id:'幻觉', category:'magic', level:'R',
    promptZh:'幻觉迷雾', promptEn:'illusion mist',
    stats:{ atk:0, def:2, spd:5, hp:0, mp:10, crit:0, dodge:10 },
    skill:{ name:'迷雾', type:'active', target:'all_enemies', effect:'敌全体命中-20% 2回合', mpCost:12 },
    description:'制造幻觉扰乱敌人' },
  { id:'瞬移', category:'magic', level:'R',
    promptZh:'短距瞬移', promptEn:'short teleport',
    stats:{ atk:0, def:0, spd:15, hp:0, mp:8, crit:0, dodge:15 },
    skill:{ name:'瞬移闪避', type:'active', target:'self', effect:'DODGE+80% 1回合', mpCost:10 },
    description:'瞬间移动避开攻击' },
  { id:'傲慢', category:'soul', level:'R',
    promptZh:'傲慢之姿', promptEn:'prideful stance',
    stats:{ atk:10, def:-5, spd:3, hp:5, mp:5, crit:5, dodge:-3 },
    description:'骄傲带来力量，也带来破绽' },
  { id:'诅咒之血', category:'fate', level:'R',
    promptZh:'诅咒之血', promptEn:'cursed blood',
    stats:{ atk:5, def:0, spd:3, hp:-5, mp:8, crit:5, dodge:3 },
    passive:'攻击附带诅咒 -5%DEF 2回合',
    description:'流淌着被诅咒的血脉' },
  // 战斗系 SR
  { id:'咆哮', category:'combat', level:'SR',
    promptZh:'战吼咆哮', promptEn:'war roar',
    stats:{ atk:12, def:5, spd:5, hp:10, mp:5, crit:5, dodge:0 },
    skill:{ name:'战吼', type:'active', target:'all_allies', effect:'全队 ATK+25% 2回合', mpCost:20 },
    description:'怒吼激励全队战力' },
  // 魔法系 SR
  { id:'分身', category:'magic', level:'SR',
    promptZh:'魔法分身', promptEn:'magic clone',
    stats:{ atk:5, def:3, spd:10, hp:5, mp:15, crit:5, dodge:10 },
    skill:{ name:'分身术', type:'active', target:'self', effect:'创造分身承受下次伤害(HP=25%)', mpCost:25 },
    description:'魔力凝聚的分身' },
  // 灵魂系 SR
  { id:'贤者', category:'soul', level:'SR',
    promptZh:'贤者智慧', promptEn:'sage wisdom',
    stats:{ atk:0, def:5, spd:5, hp:10, mp:20, crit:0, dodge:3 },
    passive:'MP 消耗 -25%',
    skill:{ name:'智慧之光', type:'active', target:'all_allies', effect:'全队 MP 回复30%，技能冷却-1回合', mpCost:15, desc:'贤者的智慧照耀全队' },
    description:'洞悉魔法本质的智慧' },
  // SSR (非元素，供高级怪物池)
  { id:'不死', category:'trait', level:'SSR',
    promptZh:'不死之身', promptEn:'undying body',
    stats:{ atk:5, def:10, spd:-5, hp:40, mp:15, crit:0, dodge:0 },
    passive:'首次致死时保留 1HP（每场一次）',
    skill:{ name:'死灵复苏', type:'active', target:'self', effect:'回复自身50%HP，清除所有负面状态', mpCost:25, desc:'不死之力涌动，重焕生机' },
    description:'拒绝死亡的意志' },
  // UR (供顶级怪物池)
  { id:'龙神血脉', category:'trait', level:'UR',
    promptZh:'龙神之血', promptEn:'dragon god blood',
    stats:{ atk:25, def:20, spd:15, hp:50, mp:30, crit:15, dodge:5 },
    passive:'龙系伤害+50%，受到伤害-20%',
    skill:{ name:'龙神咆哮', type:'active', target:'all_enemies', effect:'ATK×3.5 全体+灼烧3回合', mpCost:45, multiplier:3.5, desc:'龙神之力释放，焚尽一切', statusEffect:'burn' },
    description:'传说中龙神的后裔' },
];

// ============ 融合因子（只能通过冲突融合获得）============
export const FUSION_FACTORS: FactorDef[] = [
  { id:'蒸汽', category:'element', level:'SR', tag:'water',
    promptZh:'蒸汽爆发,白雾弥漫', promptEn:'billowing steam, mist and heat',
    stats:{ atk:15, def:3, spd:8, hp:5, mp:15, crit:3, dodge:2 },
    skill:{ name:'蒸汽爆发', type:'active', target:'all_enemies', effect:'ATK×1.8 全体攻击', mpCost:20, multiplier:1.8 },
    description:'火+水 碰撞产生的蒸汽之力' },
  { id:'融毁', category:'element', level:'SR',
    promptZh:'融毁之力,冰火交织', promptEn:'thermal shock, melting reality',
    stats:{ atk:18, def:0, spd:5, hp:0, mp:12, crit:8, dodge:0 },
    skill:{ name:'融毁射线', type:'active', target:'single_enemy', effect:'无视30%防御', mpCost:18, multiplier:2.0 },
    description:'火+冰 碰撞产生的融毁' },
  { id:'雷暴', category:'element', level:'R', tag:'thunder',
    promptZh:'雷暴降临', promptEn:'thunderstorm',
    stats:{ atk:12, def:0, spd:6, hp:0, mp:10, crit:6, dodge:0 },
    skill:{ name:'雷暴', type:'active', target:'single_enemy', effect:'ATK×1.6 + 麻痹20%', mpCost:14, multiplier:1.6 },
    description:'雷+水 引发的雷暴' },
  { id:'沙暴', category:'element', level:'R',
    promptZh:'沙暴席卷', promptEn:'sandstorm',
    stats:{ atk:10, def:5, spd:5, hp:0, mp:5, crit:3, dodge:5 },
    skill:{ name:'沙暴', type:'active', target:'all_enemies', effect:'敌方全队命中-20% 2回合', mpCost:15 },
    description:'地+风 卷起的沙暴' },
  { id:'熔岩', category:'element', level:'R', tag:'fire',
    promptZh:'熔岩之力', promptEn:'molten lava power',
    stats:{ atk:14, def:8, spd:-3, hp:5, mp:5, crit:3, dodge:0 },
    passive:'高攻高防低速',
    description:'火+地 凝结的熔岩之力' },
  { id:'霜冻', category:'element', level:'R', tag:'ice',
    promptZh:'霜冻之触', promptEn:'frost touch',
    stats:{ atk:5, def:8, spd:-3, hp:8, mp:8, crit:3, dodge:0 },
    skill:{ name:'冰冻', type:'active', target:'single_enemy', effect:'单体禁锢1回合', mpCost:16 },
    description:'冰+水 凝结的霜冻' },
  { id:'疾风', category:'combat', level:'R',
    promptZh:'疾风迅雷', promptEn:'gale force',
    stats:{ atk:8, def:0, spd:15, hp:0, mp:0, crit:5, dodge:5 },
    passive:'先制概率 +30%',
    description:'猛攻+游击 融合的极致速度' },
  { id:'狱火', category:'element', level:'SR', tag:'fire',
    promptZh:'地狱魔火化为烈焰风暴', promptEn:'purgatory firestorm, hellish blaze',
    stats:{ atk:38, def:6, spd:10, hp:15, mp:22, crit:15, dodge:0 },
    skill:{ name:'狱火风暴', type:'active', target:'all_enemies', effect:'ATK×2.5全体', mpCost:25, multiplier:2.5, desc:'地狱之火凝为风暴，焚尽众生' },
    description:'6×火堆叠 / 火+狂热 升华为狱火' },
  { id:'血清', category:'magic', level:'R',
    promptZh:'万能血清', promptEn:'universal antidote',
    stats:{ atk:3, def:5, spd:2, hp:8, mp:10, crit:0, dodge:0 },
    skill:{ name:'解毒术', type:'active', target:'all_allies', effect:'全队解毒+回复10% HP', mpCost:12 },
    description:'毒+治愈 调和的万能血清' },
  { id:'禅定', category:'soul', level:'SR',
    promptZh:'禅定之境', promptEn:'zen state',
    stats:{ atk:0, def:8, spd:5, hp:5, mp:12, crit:5, dodge:5 },
    passive:'免疫混乱,每回合MP+5',
    skill:{ name:'冥想', type:'active', target:'self', effect:'回复全部MP，下次技能伤害×2', mpCost:5, desc:'进入深层冥想，蓄力一击' },
    description:'狂热+冷静 达到的禅定' },
  { id:'殉道', category:'combat', level:'SSR',
    promptZh:'殉道之光', promptEn:'martyr\'s radiance',
    stats:{ atk:5, def:15, spd:0, hp:25, mp:10, crit:5, dodge:0 },
    passive:'替队友承受30%伤害',
    skill:{ name:'牺牲圣盾', type:'active', target:'all_allies', effect:'全队获得殉道之盾(承受一次致死伤害保留1HP)', mpCost:30, desc:'献上自身，为全队加持神圣庇护' },
    description:'守护+献祭 化作牺牲的盾' },
  { id:'黄昏', category:'element', level:'SSR',
    promptZh:'黄昏领域', promptEn:'twilight realm',
    stats:{ atk:20, def:5, spd:5, hp:10, mp:20, crit:10, dodge:3 },
    skill:{ name:'黄昏领域', type:'aura', target:'all_enemies', effect:'全局伤害+30%', mpCost:0 },
    description:'光+暗 交汇的黄昏之力' },
];

// ============ 所有因子字典 ============
export const ALL_FACTORS: Record<string, FactorDef> = {};
[...BASE_FACTORS, ...FUSION_FACTORS].forEach(f => { ALL_FACTORS[f.id] = f; });

// ============ 冲突融合规则（12组）============
export const CONFLICT_FUSIONS: ConflictFusionRule[] = [
  { inputs: ['火','水'],    output:'蒸汽',  level:'SR' },
  { inputs: ['火','冰'],    output:'融毁',  level:'SR' },
  { inputs: ['雷','水'],    output:'雷暴',  level:'R'  },
  { inputs: ['地','风'],    output:'沙暴',  level:'R'  },
  { inputs: ['火','地'],    output:'熔岩',  level:'R'  },
  { inputs: ['冰','水'],    output:'霜冻',  level:'R'  },
  { inputs: ['猛攻','游击'], output:'疾风', level:'R'  },
  { inputs: ['火','狂热'],  output:'狱火',  level:'SR' },
  { inputs: ['毒','治愈'],  output:'血清',  level:'R'  },
  { inputs: ['狂热','冷静'], output:'禅定', level:'SR' },
  { inputs: ['守护','献祭'], output:'殉道', level:'SSR'},
  { inputs: ['光','暗'],    output:'黄昏',  level:'SSR'},
];

// ============ 共鸣规则 ============
export const RESONANCES: ResonanceRule[] = [
  { name:'烈焰共鸣', title:'炎帝',   tag:'fire',    minCount:3, bonus:'火属伤害+50%' },
  { name:'深渊共鸣', title:'深渊使者', tag:'water',  minCount:3, bonus:'回合结束回复 MP 10%' },
  { name:'战神共鸣', title:'战姬',   category:'combat', minCount:3, bonus:'ATK +25%' },
  { name:'贤者共鸣', title:'贤者',   category:'magic',  minCount:3, bonus:'MP消耗 -30%' },
  { name:'极意共鸣', title:'觉者',   category:'soul',   minCount:3, bonus:'CRIT率 +15%' },
  { name:'天命共鸣', title:'天选',   category:'fate',   minCount:3, bonus:'全属性 +20%' },
  { name:'龙血觉醒', title:'龙裔',   requiredAtoms:['巨龙血脉'], tag:'fire', minCount:2, bonus:'龙息: ATK×1.8 全体 + 灼烧' },
];

// ============ 升星可选因子池（按目标星级）============
export const STAR_FACTOR_POOLS: Record<number, string[]> = {
  // ★2 升星 → 可选 N 级因子
  2: ['火','水','风','雷','冰','暗','光','地',
    '猛攻','精准','守护','游击','献祭',
    '粘液','软体','治愈','诅咒','冷静','狂热','勇敢','胆怯',
    '星之祝福','幸运','硬壳','鳞片','屏障','闪光'],
  // ★3 升星 → 可选 R 级因子
  3: ['尖刺','迅捷','召唤','增幅','慈悲','慵懒','毒','分裂',
    '反击','坚韧','毒牙','幻觉','瞬移','傲慢','诅咒之血',
    '雷暴','沙暴','熔岩','霜冻','疾风','血清','激流','暴风','雷霆','极寒','暗影','圣光','岩石'],
  // ★4 升星 → 可选 SR 级因子
  4: ['巨龙血脉','王之粘液','结界','深渊之印','王之力',
    '咆哮','分身','贤者',
    '蒸汽','融毁','狱火','禅定','深渊','飓风','劫雷','玄冰','冥暗','神辉','山岳'],
  // ★5 升星 → 可选 SSR 级因子
  5: ['不死','阳炎','沧溟','虚空风','天罚','永冻','虚无','天光','地核',
    '殉道','黄昏'],
  // ★6 升星 → 可选 UR 级因子
  6: ['龙神血脉','凤凰火','归墟','时空风暴','混沌雷','绝对零度','湮灭','创世之光','星核'],
};
